-- Phase 0 — Foundation
-- Architecture Spec Part Nine: "identity, the Agent Gateway skeleton (with only
-- My Genie's AgentDefinition populated), the Audit Log, and Row-Level Security
-- policy framework."
--
-- This migration creates the schema described in ../../schema.prisma. It was
-- generated by hand to match that file exactly, rather than by `prisma migrate
-- dev` against a live shadow database, because this build environment has no
-- Postgres connection string with credentials for the Supabase project (the
-- Supabase MCP tools deliberately do not expose the database password) and no
-- local Postgres/Docker was available to stand up a shadow database. It was
-- applied to the real Supabase project via the Supabase MCP `apply_migration`
-- tool instead of `prisma migrate deploy` for the same reason — a documented
-- deviation from the kickoff brief's Prisma-Migrate recommendation, per its own
-- "state why if you do" instruction. `schema.prisma` remains the versioned
-- source of truth; this file is kept in the standard Prisma migrations
-- directory shape so `prisma migrate resolve --applied` can adopt this exact
-- history the moment a real DATABASE_URL is available, without a schema diff.

-- ============================================================================
-- IDENTITY MODULE — Architecture Spec Part Four, "Identity module"
-- ============================================================================

CREATE TYPE "RoleType" AS ENUM (
    'LEARNER',
    'PARENT',
    'TEACHER',
    'LEARNING_COACH',
    'MENTOR',
    'COMMUNITY_MENTOR',
    'ADMINISTRATOR',
    'CURRICULUM_ARCHITECT',
    'ASSESSMENT_ARCHITECT',
    'PLATFORM_ARCHITECT',
    'FOUNDER',
    'VOLUNTEER',
    'INDUSTRY_EXPERT',
    'ALUMNI',
    'COMMUNITY_PARTNER'
);

CREATE TABLE "users" (
    "id" TEXT NOT NULL,
    "email" TEXT,
    "email_verified" TIMESTAMP(3),
    "name" TEXT,
    "image" TEXT,
    "date_of_birth" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- Auth.js (NextAuth) v5 Prisma-adapter tables. Current schema per
-- https://authjs.dev/getting-started/adapters/prisma, checked via Context7
-- 2026-08-17.
CREATE TABLE "accounts" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "provider_account_id" TEXT NOT NULL,
    "refresh_token" TEXT,
    "access_token" TEXT,
    "expires_at" INTEGER,
    "token_type" TEXT,
    "scope" TEXT,
    "id_token" TEXT,
    "session_state" TEXT,

    CONSTRAINT "accounts_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "accounts_provider_provider_account_id_key" ON "accounts"("provider", "provider_account_id");
ALTER TABLE "accounts" ADD CONSTRAINT "accounts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "sessions" (
    "id" TEXT NOT NULL,
    "session_token" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "expires" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "sessions_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "sessions_session_token_key" ON "sessions"("session_token");
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "verification_tokens" (
    "identifier" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "expires" TIMESTAMP(3) NOT NULL
);
CREATE UNIQUE INDEX "verification_tokens_identifier_token_key" ON "verification_tokens"("identifier", "token");

-- Role — typed assignment of a User to one of Blueprint 08 Part Four Section
-- Five's fifteen roles, with a validity window from day one.
CREATE TABLE "roles" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "role_type" "RoleType" NOT NULL,
    "valid_from" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "valid_to" TIMESTAMP(3),
    "granted_by_user_id" TEXT,
    "notes" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "roles_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "roles_user_id_role_type_idx" ON "roles"("user_id", "role_type");
CREATE INDEX "roles_role_type_valid_to_idx" ON "roles"("role_type", "valid_to");
ALTER TABLE "roles" ADD CONSTRAINT "roles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "roles" ADD CONSTRAINT "roles_granted_by_user_id_fkey" FOREIGN KEY ("granted_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ParentLink — the consent and recovery relationship between a minor's User
-- and a parent's User, per Blueprint 12.
CREATE TABLE "parent_links" (
    "id" TEXT NOT NULL,
    "parent_user_id" TEXT NOT NULL,
    "minor_user_id" TEXT NOT NULL,
    "consent_granted_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "revoked_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "parent_links_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "parent_links_parent_user_id_minor_user_id_key" ON "parent_links"("parent_user_id", "minor_user_id");
ALTER TABLE "parent_links" ADD CONSTRAINT "parent_links_parent_user_id_fkey" FOREIGN KEY ("parent_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "parent_links" ADD CONSTRAINT "parent_links_minor_user_id_fkey" FOREIGN KEY ("minor_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ============================================================================
-- AI GATEWAY MODULE (SKELETON) — Architecture Spec Part Four/Five
-- ============================================================================

CREATE TABLE "agent_definitions" (
    "id" TEXT NOT NULL,
    "agent_key" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "purpose" TEXT NOT NULL,
    "human_relationship" TEXT NOT NULL,
    "system_prompt" TEXT NOT NULL,
    "tool_allowlist" TEXT[],
    "data_scope" JSONB NOT NULL,
    "model_identifier" TEXT NOT NULL,
    "minimum_learner_age" INTEGER,
    "is_active" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "agent_definitions_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "agent_definitions_agent_key_key" ON "agent_definitions"("agent_key");

CREATE TABLE "agent_interactions" (
    "id" TEXT NOT NULL,
    "agent_definition_id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "acting_role_id" TEXT,
    "request_text" TEXT,
    "response_text" TEXT,
    "tool_calls" JSONB,
    "escalated" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "agent_interactions_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "agent_interactions_user_id_idx" ON "agent_interactions"("user_id");
CREATE INDEX "agent_interactions_agent_definition_id_idx" ON "agent_interactions"("agent_definition_id");
ALTER TABLE "agent_interactions" ADD CONSTRAINT "agent_interactions_agent_definition_id_fkey" FOREIGN KEY ("agent_definition_id") REFERENCES "agent_definitions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "agent_interactions" ADD CONSTRAINT "agent_interactions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "agent_interactions" ADD CONSTRAINT "agent_interactions_acting_role_id_fkey" FOREIGN KEY ("acting_role_id") REFERENCES "roles"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ============================================================================
-- AUDIT LOG — Architecture Spec Part Ten / Part Eight
-- ============================================================================

CREATE TYPE "AuditEventType" AS ENUM (
    'AGENT_INTERACTION',
    'ROLE_GRANTED',
    'ROLE_REVOKED',
    'PARENT_LINK_CREATED',
    'PARENT_LINK_REVOKED',
    'CERTIFICATION_DECISION'
);

CREATE TABLE "audit_log_entries" (
    "id" TEXT NOT NULL,
    "event_type" "AuditEventType" NOT NULL,
    "actor_user_id" TEXT,
    "target_user_id" TEXT,
    "agent_interaction_id" TEXT,
    "summary" TEXT NOT NULL,
    "metadata" JSONB,
    "occurred_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "audit_log_entries_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "audit_log_entries_agent_interaction_id_key" ON "audit_log_entries"("agent_interaction_id");
CREATE INDEX "audit_log_entries_target_user_id_idx" ON "audit_log_entries"("target_user_id");
CREATE INDEX "audit_log_entries_event_type_idx" ON "audit_log_entries"("event_type");
ALTER TABLE "audit_log_entries" ADD CONSTRAINT "audit_log_entries_actor_user_id_fkey" FOREIGN KEY ("actor_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "audit_log_entries" ADD CONSTRAINT "audit_log_entries_target_user_id_fkey" FOREIGN KEY ("target_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "audit_log_entries" ADD CONSTRAINT "audit_log_entries_agent_interaction_id_fkey" FOREIGN KEY ("agent_interaction_id") REFERENCES "agent_interactions"("id") ON DELETE SET NULL ON UPDATE CASCADE;
